# Generated by Django 3.1.2 on 2021-05-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210508_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_borrowed', 'See book as borrowed'))},
        ),
    ]
