# Generated by Django 3.1.2 on 2021-05-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210509_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_manage_authors', 'Can manage authors'),)},
        ),
    ]
